### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by nctrnlgz** [DannyZB/seedr_chrome#1]
Hi man, i am creating a android client for seedr and came across this repository.
Just wanted to ask if i can use this is API?

**Comment by DannyZB** [comment]
Hello Mahto,

Wait with the Android client,
we will be releasing an official -public- oAuth API.

This API is meant for use inside the comapny as it does not have proper access controls for third-party addons(an approval page for users etc')

**Comment by nctrnlgz** [comment]
Awesome, when can we expect it ?

Please release it sooner, i wanted an app for seedr since 2015, but now because of unavailabilty of any such app i have decided to make it myself :joy: 

I just want ability to add torrents from my phone to seedr like the chrome extension :weary:

**Comment by nctrnlgz** [comment]
Any Update ?

**Comment by DannyZB** [comment]
We are rewriting seedr and the api.
When its ready you will get access

**Comment by nctrnlgz** [comment]
cool!

**Comment by nctrnlgz** [comment]
any update?

**Comment by DannyZB** [comment]
Hey,

We will be releasing several upgrades in January, the proposed API might be implemented during. High likelihood it will be out before the end of february.

You will be let know when we have a prototype
